In [19]:
# Imports
import numpy as np
import cv2
from sklearn import preprocessing
import skimage
from instaFilters import gotham, gingham, clarendon, juno, lark, reyes

# return scene probability vector
# suppose we have x supported scenes
NUM_SCENES = 9
FEATURE_LENGTH = 60
def scene_vector(image):
    scene_prob = np.zeros(NUM_SCENES)
    scene_prob[0] = 1
    return scene_prob[..., np.newaxis] # NUM_SCENES x 1

from skimage.color import rgb2hsv
# normalized feature vector
# expects float32 image
def get_features(image):
    # just a color histogram for now (remember to test hsv)
    # https://docs.opencv.org/3.1.0/d1/db7/tutorial_py_histogram_begins.html
    # remember mask param
#     image = rgb2hsv(image).astype('float32')
    # Do we normalize per histogram, or overall? (overall for performance for now)
    hist_1 = cv2.calcHist([image], [0], None, [25], [0, 1])
    hist_2 = cv2.calcHist([image], [1], None, [25], [0, 1])
    hist_3 = cv2.calcHist([image], [2], None, [25], [0, 1])
    return preprocessing.normalize(np.concatenate((hist_1, hist_2, hist_3)), axis=0)

# return dictionary of 'avg' histogram/feature vector of scenes given images (key = scenes)
# this should probably be some NN
def scene_features(images):
    scene_features = np.zeros((NUM_SCENES, FEATURE_LENGTH)) 
    for image in images:
        scene = scene_vector(image)
        feature = get_features(image.astype('float32'))
        img_hist = np.matmul(scene, feature.T) # image's contributions to scene features - ith row is ith scene's hist
        scene_features += img_hist
        # matrix multiply scene and feature
    # Todo: normalize each set of interesting info
    return preprocessing.normalize(scene_features)



In [21]:
# return array of distribution vectors for each filter fn in FILTERS
# Todo - add gotham back
FILTERS = [gotham, gingham, clarendon, juno, lark, reyes]
SCENES = ['abbey', 'airport_terminal', 'amphitheater', 'amusement_park', 'aquarium', 'aqueduct', 'art_gallery', 'assembly_line', 'auditorium']
CORPUS_CHARACTERISTIC = './corpus_characteristics.npy'
DATA_DIR = 'data/images/train/a/abbey'
def create_scene_characteristics():
    import glob
    filelist = glob.glob('{}/*.jpg'.format(DATA_DIR))
    images = np.array([cv2.imread(fname) for fname in filelist])
    images = np.asarray([skimage.img_as_float(image).astype('float32') for image in images])
    # write characteristics to file
    filtered_images = [images]
    for filt in FILTERS:
        filtered_images.append(filt(images))
    feature_distributions = []
    for images in filtered_images:
        feature_distributions.append(scene_features(images))
    all_characteristics = np.asarray(feature_distributions)
    np.save(CORPUS_CHARACTERISTIC, all_characteristics)
    # shape is (filters + 1) * (scenes) * (feature length)
def load_scene_characteristics():
    return np.load(CORPUS_CHARACTERISTIC)

create_scene_characteristics()

(1000, 128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)


(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 128, 3)
(128, 

ValueError: operands could not be broadcast together with shapes (9,60) (9,75) (9,60) 

In [ ]:
# Ported from stack overflow
def softmax(x):
    """Compute softmax values for each sets of scores in x."""
    e_x = np.exp(x - np.max(x))
    return e_x / e_x.sum(axis=0)

def classifyFilter(img, characteristics):
    scene_vec = scene_vector(img)[0]
#     print(scene_vec)
    # Take dominant scene for now and reference just that
    scene = np.argmax(scene_vec)
    scene_filter_features = characteristics[:, scene]
    img_features = get_features(skimage.img_as_float(img).astype('float32'))
    error_vec = scene_filter_features - img_features.T
#     print(scene_filter_features.shape)
#     print(img_features.T.shape)
#     print(error_vec.shape)
#     print(error_vec)
    errors = np.linalg.norm(error_vec, axis=1)
    scores = 1 / errors
#     print(scores)
    return softmax(scores)
    
def generate_test_images(fn):
    image = cv2.imread(fn)
    fn_base = fn.split('.')[0]
    import imageio
    imageio.imwrite('data/tests/{}_base.jpg'.format(fn_base), image)
    print(image.shape)
    image = skimage.img_as_float(image).astype('float32')
    from skimage import img_as_ubyte
    for i, filt in enumerate(FILTERS):
        imageio.imwrite('data/tests/{}_{}.jpg'.format(fn_base, i), img_as_ubyte(filt(image)))
generate_test_images('abbey_test.jpg')
    
def driver():
    characteristics = load_scene_characteristics()
    img = cv2.imread('data/tests/abbey_test_base.jpg')
    x = classifyFilter(img, characteristics)
    print('test_filter_none')
    print(np.argsort(x)[::-1])
    for filt_index in range(len(FILTERS)):
        img = cv2.imread('data/tests/abbey_test_{}.jpg'.format(filt_index))
        x = classifyFilter(img, characteristics)
        print('test_filter_{}'.format(filt_index + 1))
        print(x)
        print(np.argsort(x)[::-1])


In [18]:
driver()

test_filter_none
[0 5 2 4 3 6 1]
test_filter_1
[0 4 5 3 2 1 6]
test_filter_2
[2 0 3 6 5 4 1]
test_filter_3
[0 5 4 2 3 6 1]
test_filter_4
[5 4 0 3 2 1 6]
test_filter_5
[5 0 4 3 2 6 1]
test_filter_6
[2 6 0 3 5 4 1]
